### PR TITLE
Changed numbered list to bullets

### PR DESCRIPTION
**Pull request by kescobo**
Numbered list is probably better, but is not displaying properly on the website. When rendered in Github under "preview changes," it looks fine, but on the website all of the numbers are "1."

Github preview: 
screen shot 2015-12-02 at 4 18 08 pm
Website (using Chrome): 
screen shot 2015-12-02 at 4 17 58 pm

### CODE REVIEW

**Comment by gregcaporaso** [comment]
Thanks for the PR @kescobo! Weird, I can't reproduce this locally (the numbers look fine for me), so it must be related to our markdown to html conversion. I think the bullets are fine here though as I don't refer to those numbers anywhere, and there is no inherent order, so I'll just go ahead and merge this.

Note that the change won't be live on the website until the next release (which should be before mid-January).

**Comment by kescobo** [comment]
No sweat, looking forward to the rest of the book!

(PS - am I supposed to close the PR, or is that up to you?)

**Comment by gregcaporaso** [comment]
I'll merge/close it. The tests aren't passing right now though (due to an
unrelated issue) so I'm going to wait until I have that working again.

**Comment by gregcaporaso** [comment]
@kescobo, thanks again for this pull request. I did a big re-write of this chapter over the last few weeks, and this list ended up going away, so I have to close this PR as it's no longer relevant. I hope to have other contributions from you in the future, sorry this one didn't make it in!

**Comment by kescobo** [comment]
No sweat! I've ben meaning to get farther through, but have been having problems with the install. Will post it as an issue soon.

**Pull request closed without merging**
