### PR TITLE
Fix a couple typos and grammar

### PR DESCRIPTION
**Pull request by anderspitman**
I also noticed that `blosum50` is stilled pulled from `iab`, even though we have a copy in ``skbio.alignment._pairwise``. Is this intentional?

### CODE REVIEW

**Comment by anderspitman** [comment]
Don't merge this yet. Still finding a few.

**Comment by anderspitman** [comment]
Alright, those are all the ones I found while reading through IAB. Excellent book @gregcaporaso!

**Comment by ebolyen** [comment]
I don't believe `blosum50` is publicly importable in skbio yet. We don't have a real concept of substitution matrices yet, but it is planned. As a package convention, anything in a file starting with an `_` isn't "public" unless it is imported by the subpackage init (which are always considered public).

**Comment by gregcaporaso** [comment]
That's correct re: blosum50 - we'll want to update this when we have that importable (biocore/scikit-bio#161). 

@anderspitman, this isn't merge-able due to some other updates that I've made. Unfortunately resolving merge conflicts in IPython Notebooks is currently a nightmare. Want to see if it'll be easier to fix this pull request, or just make the changes in a new one? 

Thanks for the pull request, sorry it's going to be a pain to get merged!

**Comment by anderspitman** [comment]
@gregcaporaso I don't think it will be too much of a problem to add these changes to the latest version. I can even wait until a more convenient time if that's easier.

**Comment by gregcaporaso** [comment]
@anderspitman, that'd be great. I'm going to be working on the clustering and biological diversity chapters over the weekend, so maybe best is if you split this into a couple of different PRs, holding off on making the edits to those two chapters till I get through my major edits to those. Would that work?

**Comment by anderspitman** [comment]
@gregcaporaso sounds good. I'll probably just do it all in one batch when you're done.

**Comment by gregcaporaso** [comment]
@anderspitman, the issue is going to be that it's never really "done", so we'll probably need to do things like this on a chapter-by-chapter basis instead of in big chunks. 

I need to add a ``CONTRIBUTING.md`` for IAB, but figuring out how contributing will work is going to be something that develops over time. Sadly, because of how hard it currently is to diff IPython Notebooks (I tried [nbdiff](http://nbdiff.org/), and it doesn't seem to work with recent versions of IPython Notebook, but I need to explore more) we might need to go with some kind of "checkout" system, to ensure that only one person is ever working on a single notebook at a time.

**Comment by gregcaporaso** [comment]
@anderspitman, can you resubmit these changes using the new "edit" links in the text via http://readiab.orb/book/latest (note that the dns is temporarily down right now - in the meantime you could find the content [here](http://readiab.org.s3-website-us-west-1.amazonaws.com/book/latest/))?

**Comment by anderspitman** [comment]
@gregcaporaso will do

**Pull request closed without merging**
